# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "archive the app, but do not create a DMG"
  lane :development do
    gym
  end

  desc "archive the app, and create a DMG"
  lane :release do
    gym
    Dir.chdir("..") do
      sh "./BuildTools/create-dmg.sh"
    end
  end
end
