name: test-mac-app
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - run: fastlane test
        env:
          FASTLANE_MATCH_REPO_BASIC_AUTH: ${{ secrets.FASTLANE_MATCH_REPO_BASIC_AUTH }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}